-- Change 03 (course-deck-mgmt): courses and decks.

CREATE TABLE courses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title      VARCHAR(200) NOT NULL,
    visibility VARCHAR(20)  NOT NULL DEFAULT 'PRIVATE',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_courses_visibility CHECK (visibility IN ('PUBLIC', 'PRIVATE'))
);

CREATE TABLE decks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id  BIGINT       NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    title      VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_courses_owner_id ON courses (owner_id);
CREATE INDEX idx_courses_visibility ON courses (visibility);
CREATE INDEX idx_decks_course_id ON decks (course_id);
