-- Change 04 (flashcard-crud): cards (shared content; no per-user study state yet).

CREATE TABLE cards (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id    BIGINT        NOT NULL REFERENCES decks (id) ON DELETE CASCADE,
    front      VARCHAR(2000) NOT NULL,
    back       VARCHAR(2000) NOT NULL,
    notes      VARCHAR(4000),
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_cards_deck_id ON cards (deck_id);
