-- Change 05 (study-mode-basic): records of completed study runs (no per-card state).

CREATE TABLE study_sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    deck_id       BIGINT      NOT NULL REFERENCES decks (id) ON DELETE CASCADE,
    total_cards   INTEGER     NOT NULL,
    correct_count INTEGER     NOT NULL,
    finished_at   TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_study_sessions_counts CHECK (correct_count >= 0 AND correct_count <= total_cards)
);

CREATE INDEX idx_study_sessions_user_id ON study_sessions (user_id);
