-- Change 06 (ai-quota-infra): a record of every AI call, for cost tracking and quotas.

CREATE TABLE ai_usage_log (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    feature_key        VARCHAR(50)   NOT NULL,
    input_tokens       INTEGER       NOT NULL,
    output_tokens      INTEGER       NOT NULL,
    estimated_cost_usd NUMERIC(12, 6) NOT NULL,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Quotas sum a user's tokens within the current month.
CREATE INDEX idx_ai_usage_log_user_created ON ai_usage_log (user_id, created_at);
