-- Change 08 (spaced-repetition): per-user SM-2 scheduling state, one row per (user, card).
-- A missing row means the card is "new" for that user; the row is created on first review.

CREATE TABLE user_card_state (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT           NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    card_id          BIGINT           NOT NULL REFERENCES cards (id) ON DELETE CASCADE,
    ease_factor      DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    interval_days    INTEGER          NOT NULL DEFAULT 0,
    repetitions      INTEGER          NOT NULL DEFAULT 0,
    due_at           TIMESTAMPTZ      NOT NULL,
    last_reviewed_at TIMESTAMPTZ      NOT NULL,
    created_at       TIMESTAMPTZ      NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ      NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_card UNIQUE (user_id, card_id)
);

-- The due queue selects a user's rows whose due_at has passed.
CREATE INDEX idx_user_card_state_user_due ON user_card_state (user_id, due_at);
